import { useState } from 'react'
import { ArrowDown, BrainCircuit, CheckCircle2, Database, GitMerge, RotateCw, ShieldAlert } from 'lucide-react'
import { DataSourceCard } from '../components/cards/DataSourceCard'
import { dataSources } from '../data/mockData'

const stages = [{ icon: Database, title: 'AI data fusion engine', detail: 'Spatially and temporally aligned inputs', tone: 'text-accent' }, { icon: BrainCircuit, title: 'Rainfall prediction', detail: 'Heavy rainfall probability and intensity', tone: 'text-high' }, { icon: ShieldAlert, title: 'Flood risk engine', detail: 'Elevation, terrain and historical context', tone: 'text-severe' }, { icon: CheckCircle2, title: 'Early warning', detail: 'Actionable zones and risk levels', tone: 'text-safe' }]

export function DataFusionPage() {
	const [refreshing, setRefreshing] = useState(false)
	function refreshSources() { setRefreshing(true); window.setTimeout(() => setRefreshing(false), 700) }
	return <div className="flex flex-col gap-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Observe · Data architecture</p><h1 className="page-title mt-2">Multi-Source Weather Intelligence</h1><p className="page-subtitle">AquaSentinel turns incomplete weather signals into one operational view for earlier decisions.</p></div><button type="button" className="btn" onClick={refreshSources} disabled={refreshing}><RotateCw size={14} className={refreshing ? 'is-spinning' : ''} />{refreshing ? 'Checking feeds' : 'Refresh feeds'}</button></header><section className="glass-panel"><div className="panel-head"><div><h2 className="panel-title flex items-center gap-2"><GitMerge size={15} className="text-accent" />Observe → predict → warn</h2><p className="panel-kicker">Five mock feeds flow through two intelligence engines to produce an early warning.</p></div><span className="badge"><span className="status-dot is-accent" />Fusion nominal</span></div><div className="panel-body flex flex-col items-center gap-3"><div className="grid w-full gap-2 md:grid-cols-5">{dataSources.map((source) => <DataSourceCard key={source.id} source={source} compact />)}</div><ArrowDown className="flow-dash" size={22} />{stages.map(({ icon: Icon, title, detail, tone }, index) => <div key={title} className="w-full max-w-xl rounded-xl border border-line-strong bg-surface-1/60 px-5 py-4 text-center"><Icon size={20} className={`mx-auto ${tone}`} /><div className="mt-2 text-[0.6rem] font-bold tracking-[0.18em] text-accent">STAGE {String(index + 1).padStart(2, '0')}</div><div className="mt-1 font-bold uppercase tracking-[0.12em] text-ink">{title}</div><div className="mt-1 text-xs text-ink-3">{detail}</div>{title !== 'Early warning' && <ArrowDown className="flow-dash mx-auto mt-3" size={16} />}</div>)}</div></section><section className="grid gap-5 xl:grid-cols-2"><div className="glass-panel"><div className="panel-head"><h2 className="panel-title">Why multi-source?</h2></div><div className="panel-body"><p className="text-sm leading-relaxed text-ink-2">Individual weather sources provide incomplete information. AquaSentinel combines multiple sources to improve spatial, temporal and predictive awareness, then exposes the evidence behind each warning.</p></div></div><div className="glass-panel"><div className="panel-head"><h2 className="panel-title">Data status</h2></div><div className="panel-body grid gap-2">{dataSources.map((source) => <div key={source.id} className="flex items-center justify-between rounded-lg border border-line-subtle bg-surface-1/30 px-3 py-2 text-sm"><span className="font-bold text-ink">{source.code}</span><span className="flex items-center gap-2 text-safe"><span className="status-dot" />Connected</span></div>)}</div></div></section></div>
}